// Pure Data Store
export const WeatherData = {
  current: {
    temperature: 34,
    condition: "Cerah Berawan",
    feelsLike: 39,
    humidity: 75,
    uvIndex: 8,
    windSpeed: 12,
    location: "Jepara",
    pressure: 1013,
    visibility: 5,
    airQuality: "Baik",
  },
  forecast: [
    {
      day: "Hari Ini",
      date: "16 Okt",
      high: 34,
      low: 27,
      condition: "sunny",
      icon: "☀️",
      precipitation: 0,
      wind: 12,
    },
    {
      day: "Besok",
      date: "17 Okt",
      high: 32,
      low: 26,
      condition: "partly-cloudy",
      icon: "⛅",
      precipitation: 10,
      wind: 15,
    },
    {
      day: "Sabtu",
      date: "18 Okt",
      high: 31,
      low: 25,
      condition: "rainy",
      icon: "🌧️",
      precipitation: 80,
      wind: 20,
    },
    {
      day: "Minggu",
      date: "19 Okt",
      high: 31,
      low: 25,
      condition: "stormy",
      icon: "⛈️",
      precipitation: 90,
      wind: 25,
    },
    {
      day: "Senin",
      date: "20 Okt",
      high: 32,
      low: 26,
      condition: "partly-cloudy",
      icon: "⛅",
      precipitation: 20,
      wind: 18,
    },
    {
      day: "Selasa",
      date: "21 Okt",
      high: 35,
      low: 29,
      condition: "sunny",
      icon: "☀️",
      precipitation: 0,
      wind: 10,
    },
    {
      day: "Rabu",
      date: "22 Okt",
      high: 34,
      low: 27,
      condition: "sunny",
      icon: "☀️",
      precipitation: 5,
      wind: 14,
    },
  ],
  recommendations: [
    {
      category: "Hidrasi & Nutrisi",
      icon: "💧",
      priority: "high",
      items: [
        "Minum air putih minimal 1 gelas setiap jam",
        "Konsumsi buah-buahan kaya air seperti semangka atau melon",
      ],
    },
    {
      category: "Aktifitas Luar Ruangan",
      icon: "☀️",
      priority: "high",
      items: [
        "Hindari aktivitas fisik berat antara pukul 11:00 - 15.00",
        "Jika harus keluar, gunakan topi lebar dan cari tempat teduh",
      ],
    },
  ],
  heatmap: {
    locations: [
      { name: "Pusat Kota", temp: 38, lat: -6.5944, lng: 110.6717 },
      { name: "Pantai Kartini", temp: 32, lat: -6.6, lng: 110.65 },
      { name: "Bandara", temp: 35, lat: -6.58, lng: 110.68 },
      { name: "Pelabuhan", temp: 30, lat: -6.59, lng: 110.66 },
      { name: "Pasar", temp: 36, lat: -6.595, lng: 110.672 },
    ],
  },
};

// Global Exposure for Debugging
window.WeatherData = WeatherData;
